name: Trigger auto deployment for oneday-webportal

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/oneday-webportal-AutoDeployTrigger-8232b7df-76c6-409f-bc19-cb314e359991.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ONEDAYWEBPORTAL_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ONEDAYWEBPORTAL_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ONEDAYWEBPORTAL_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: onedaywebportal.azurecr.io
          registryUsername: ${{ secrets.ONEDAYWEBPORTAL_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ONEDAYWEBPORTAL_REGISTRY_PASSWORD }}
          containerAppName: oneday-webportal
          resourceGroup: oneday
          imageToBuild: onedaywebportal.azurecr.io/oneday-webportal:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


